# Generated by Django 4.2.9 on 2024-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='times_used',
        ),
        migrations.AddField(
            model_name='recipeproduct',
            name='cooked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.FloatField(),
        ),
    ]
