# Generated by Django 4.2.9 on 2024-01-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_product_times_used_recipeproduct_cooked_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='recipeproduct',
            unique_together={('recipe', 'product')},
        ),
    ]
