# Generated by Django 4.2.9 on 2024-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeproduct_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooked',
            field=models.IntegerField(default=0),
        ),
    ]
