# Generated by Django 4.2.9 on 2024-01-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_product_cooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeproduct',
            name='cooked_count',
        ),
    ]
